### ISSUE TITLE
ITM is not Sync while Log trait requires it

### ISSUE THREAD

**Issue by DoumanAsh** [DoumanAsh/cortex-m-log#2]
Most likely writes underlying `Stim` should be guarded by some simple atomic and `Itm` destination can be marked as Sync

**Comment by MabezDev** [comment]
Are there any work around for this in the short term? Or any plans to fix this?

**Comment by DoumanAsh** [comment]
Sorry, I didn't work on it at all.
I'm not sure how to approach this problem on embedded Rust

**Comment by DoumanAsh** [comment]
@MabezDev Take a look at `ItmSync` https://github.com/DoumanAsh/cortex-m-log/commit/0375e74262a175c567eab4ffe5f14ac6dd2b2ec8

I'm still thinking of how to do it better, but let me know if it would suit your needs.
There is separate printer now, but it otherwise is the same

**Comment by MabezDev** [comment]
@DoumanAsh just tested on my board and it works very well. Thanks 

If/when you are happy with the implementation could it be put into a new release?

p.s I'll close my PR now.

**Comment by DoumanAsh** [comment]
Ok, I'll need to think a bit and will release new version soon

**Comment by MabezDev** [comment]
Have you had a chance to think it through? I don't want to rush you of course :)

**Comment by DoumanAsh** [comment]
Damn, sorry. I came to conclusion but forgot.

I'm releasing `0.4.0` with the current version.
I want to avoid code reduce code duplication but in this case it is too difficult.
