### ISSUE TITLE
Cortex-M0+ and the log-integration feature

### ISSUE THREAD

**Issue by tkeksa** [DoumanAsh/cortex-m-log#5]
The log-integration feature can not be enabled for the thumbv6m-none-eabi target (build fails).
The log::set_logger() is called which is available only if #[cfg(atomic_cas)].
The unsafe log::set_logger_racy() could be used on platforms without atomic_cas.
Do you plan to support the log-integration feature on Cortex-M0+ somehow?

**Comment by DoumanAsh** [comment]
Yes, ideally we could just add cfg to use `set_logger` when it is available, and use `set_logger_racy` otherwise.

You're welcome to make such PR, otherwise I'll take a look at it on weekend.

**Comment by tkeksa** [comment]
As I am not fully sure how to proceed with unsafe I would let you do it in your way.

**Comment by DoumanAsh** [comment]
Actually it is quite trivial https://github.com/DoumanAsh/cortex-m-log/commit/725631573eadd9d1a07901c73db7f451302527cc

It compiles for m0, but I'm not sure if llvm guarantees about ordering will uphold.
But if they do uphold then even multiple calls to `init` would be safe, though there will be only 1 actual set of logger.

P.s. I got ordering wrong(it should be swapped)

**Comment by DoumanAsh** [comment]
@tkeksa please check master branch and that it works as expected.
I do not have m0 device.

**Comment by tkeksa** [comment]
It does work well. Great!

**Comment by DoumanAsh** [comment]
I released [0.6.1](https://crates.io/crates/cortex-m-log/0.6.1) wit this correction
